sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "10"

branches:
  only:
    - /.*/

before_script:
  - npm install

script:
  - ng build --prod --aot
  - npm run lint
  - ng test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

env:
  global:
    - NG_CLI_ANALYTICS=ci
